[tool.poetry]
name = "bertrend"
version = "0.1.0"
description = "BERTrend analyses topic evolution over time using state-of-the-art transformer models: topic modelling and LLM"
authors = ["Jérôme Picault <jerome.picault@rte-france.com>", "Guillaume Grosjean <guillaume.grosjean@rte-france.com>"]
license = "LICENSE.md"
readme = "README.md"
repository = "https://github.com/rte-france/BERTrend"
keywords = ["topics", "BERTopic", "transformers", "weak signals"]
packages = [
    { include = "bertrend" },
    { include = "bertrend_apps" },
]
exclude = [ "data" ]

[tool.poetry.dependencies]
python = "^3.11"
ipython = "^8.28.0"

# A list of all the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
pytest = { version = "^8.3.3", optional = true}

# These packages are mandatory and form the core of this package’s distribution.
accelerate = "^0.34.2"
arxiv = "^2.1.3"
bertopic = "^0.16.3"
black = "^24.10.0"
dateparser = "^1.2.0"
datamapplot = "0.3.0"
feedparser = "^6.0.11"
gensim = "4.3.2"
googlenewsdecoder = "^0.1.6"
google-api-python-client = "^2.148.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.1"
goose3 = "^3.1.19"
hdbscan = "^0.8.38.post2"
langchain-community = "^0.3.1"
langchain-chroma = "^0.1.4"
langchain-openai = "^0.2.2"
langdetect = "^1.0.9"
llama-index = "^0.11.16"
llama-index-core = "^0.11.16"
llvmlite = "^0.43.0"
loguru = "^0.7.2"
lxml-html-clean = "^0.2.2"
jsonlines = "^4.0.0"
markdown = "^3.7"
newscatcherapi = "^0.7.3"
newspaper4k = "^0.9.3.1"
nltk = "^3.9.1"
openai = "^1.51.1"
pandas = "^2.2.2"
plotly = "^5.24.1"
plotly-resampler = "^0.10.0"
pygooglenews = {git = "https://github.com/picaultj/pygooglenews.git", rev = "master"}
scipy = {version = "1.12", python=""}
scikit-learn = "^1.5.2"
sentence-transformers = "3.0.1"
requests = "^2.32.3"
seaborn = "^0.13.2"
sentencepiece = "^0.2.0"
streamlit = "^1.39.0"
torch = "^2.4.1"
tqdm = "^4.66.5"
tiktoken = "^0.8.0"
tokenizers = "<0.20.0"
umap-learn = "^0.5.6"


[tool.poetry.extras]
tests = ["pytest"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
